name: motorshed
channels:
  - conda-forge
dependencies:
  - black
  - imgaug
  - jupyter
  - osmnx
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - tqdm
  - pip:
    - contexttimer
    - requests
    - requests_cache
    - motorshed
